-- ============================================================
-- Baseline migration: prod schema captured 2026-03-25
-- Source: zehwkrndfwjrvqdckepu (ameropa-farmer / PROD)
-- ============================================================

-- ============================================================
-- Sequences
-- ============================================================

CREATE SEQUENCE IF NOT EXISTS public.contract_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE IF NOT EXISTS public.farmer_rewards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- ============================================================
-- Tables (must come before SQL-language functions that reference them)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid NOT NULL,
    email text,
    role text NOT NULL DEFAULT 'farmer'::text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    status text NOT NULL DEFAULT 'active'::text,
    invited_by uuid,
    invited_at timestamp with time zone,
    sharp_id text,
    full_name text,
    telefon text,
    judet text,
    CONSTRAINT profiles_pkey PRIMARY KEY (id),
    CONSTRAINT profiles_status_check CHECK (status = ANY (ARRAY['active'::text, 'disabled'::text])),
    CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
    CONSTRAINT profiles_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id)
);

CREATE TABLE IF NOT EXISTS public.bids (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    farmer_id uuid DEFAULT auth.uid(),
    product text NOT NULL DEFAULT 'Not Null'::text,
    quantity numeric,
    price numeric,
    delivery_start date,
    delivery_end date,
    status text,
    created_at timestamp with time zone DEFAULT now(),
    parity text,
    freight_cost numeric,
    counter_price numeric,
    farmer_email text,
    final_price numeric,
    contract_no text,
    accepted_at timestamp with time zone,
    delivery_location text,
    loading_location text,
    CONSTRAINT bids_pkey PRIMARY KEY (id),
    CONSTRAINT bids_contract_no_key UNIQUE (contract_no)
);

CREATE TABLE IF NOT EXISTS public.farmer_rewards (
    id bigint NOT NULL DEFAULT nextval('public.farmer_rewards_id_seq'::regclass),
    farmer_id uuid,
    reward_type text NOT NULL,
    unlocked_at timestamp with time zone DEFAULT now(),
    used boolean DEFAULT false,
    target_t integer,
    bonus_eur numeric,
    bonus_tonnes integer,
    lock_product text,
    lock_days integer,
    lock_limit_tonnes integer,
    CONSTRAINT farmer_rewards_pkey PRIMARY KEY (id),
    CONSTRAINT farmer_rewards_farmer_id_fkey FOREIGN KEY (farmer_id) REFERENCES auth.users(id)
);

CREATE TABLE IF NOT EXISTS public.silo_price_configs (
    id uuid NOT NULL DEFAULT extensions.uuid_generate_v4(),
    silo_name text NOT NULL,
    product_type text NOT NULL,
    offset_value numeric NOT NULL,
    currency text NOT NULL DEFAULT 'EUR'::text,
    updated_at timestamp with time zone DEFAULT now(),
    manual_price numeric,
    notes text,
    CONSTRAINT silo_price_configs_pkey PRIMARY KEY (id),
    CONSTRAINT unique_silo_product UNIQUE (silo_name, product_type)
);

CREATE TABLE IF NOT EXISTS public.commodities (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name text NOT NULL,
    price numeric NOT NULL,
    last_updated timestamp with time zone DEFAULT now(),
    CONSTRAINT commodities_pkey PRIMARY KEY (id),
    CONSTRAINT commodities_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.rate_limits (
    key text NOT NULL,
    count integer NOT NULL DEFAULT 1,
    window_start timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT rate_limits_pkey PRIMARY KEY (key)
);

-- Non-unique index
CREATE INDEX IF NOT EXISTS rate_limits_window_idx ON public.rate_limits USING btree (window_start);

-- ============================================================
-- Functions (after tables so SQL-language functions validate correctly)
-- ============================================================

CREATE OR REPLACE FUNCTION public.is_admin(uid uuid)
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
  select exists (
    select 1 from public.profiles p
    where p.id = uid and p.role = 'admin'
  );
$$;

CREATE OR REPLACE FUNCTION public.generate_contract_no(prefix text DEFAULT 'AMRP'::text)
RETURNS text
LANGUAGE plpgsql
AS $$
declare
  n bigint;
begin
  n := nextval('public.contract_seq');
  return prefix || '-' || lpad(n::text, 5, '0');
end;
$$;

CREATE OR REPLACE FUNCTION public.assign_contract_no_on_accept()
RETURNS trigger
LANGUAGE plpgsql
AS $$
begin
  if (new.status = 'accepted')
     and (old.status is distinct from new.status)
     and new.contract_no is null then
    new.contract_no := public.generate_contract_no('AMRP');
    new.accepted_at := now();
  end if;
  return new;
end;
$$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role, status)
  VALUES (NEW.id, NEW.email, 'farmer', 'active')
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

-- ============================================================
-- Triggers
-- ============================================================

CREATE OR REPLACE TRIGGER trg_assign_contract_no
    BEFORE UPDATE ON public.bids
    FOR EACH ROW EXECUTE FUNCTION public.assign_contract_no_on_accept();

CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================================
-- Row Level Security
-- ============================================================

ALTER TABLE public.bids ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.farmer_rewards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.silo_price_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.commodities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rate_limits ENABLE ROW LEVEL SECURITY;

-- Policies: bids
CREATE POLICY admin_select_all_bids ON public.bids
    FOR SELECT USING (public.is_admin(auth.uid()));

CREATE POLICY admin_update_all_bids ON public.bids
    FOR UPDATE USING (public.is_admin(auth.uid()))
    WITH CHECK (public.is_admin(auth.uid()));

CREATE POLICY farmer_insert_own_bids ON public.bids
    FOR INSERT WITH CHECK (auth.uid() = farmer_id);

CREATE POLICY farmer_select_own_bids ON public.bids
    FOR SELECT USING (auth.uid() = farmer_id);

CREATE POLICY farmer_update_own_bids ON public.bids
    FOR UPDATE
    USING ((auth.uid() = farmer_id) AND (status = 'countered'::text))
    WITH CHECK ((auth.uid() = farmer_id) AND (status = ANY (ARRAY['farmer_countered'::text, 'accepted'::text, 'rejected'::text])));

-- Policies: commodities
CREATE POLICY admin_write_commodities ON public.commodities
    FOR ALL USING (public.is_admin(auth.uid()))
    WITH CHECK (public.is_admin(auth.uid()));

CREATE POLICY authenticated_read_commodities ON public.commodities
    FOR SELECT TO authenticated USING (true);

-- Policies: farmer_rewards
CREATE POLICY farmer_rewards_select_own ON public.farmer_rewards
    FOR SELECT USING (farmer_id = auth.uid());

-- Policies: profiles
CREATE POLICY admin_read_all_profiles ON public.profiles
    FOR SELECT TO authenticated USING (public.is_admin(auth.uid()));

CREATE POLICY admin_update_profiles ON public.profiles
    FOR UPDATE USING (public.is_admin(auth.uid()))
    WITH CHECK (public.is_admin(auth.uid()));

CREATE POLICY users_can_read_own_profile ON public.profiles
    FOR SELECT TO authenticated USING (id = auth.uid());

-- Policies: silo_price_configs
CREATE POLICY admin_write_silo_prices ON public.silo_price_configs
    FOR ALL USING (public.is_admin(auth.uid()))
    WITH CHECK (public.is_admin(auth.uid()));

CREATE POLICY authenticated_read_silo_prices ON public.silo_price_configs
    FOR SELECT TO authenticated USING (true);

-- Note: rate_limits has RLS enabled but intentionally no policies.
-- It is only accessible via service_role (Edge Functions).
-- Advisory: https://supabase.com/docs/guides/database/database-linter?lint=0008_rls_enabled_no_policy
